import { sql, type RawBuilder } from "kysely";
import type { DatabaseContext } from "../../db/database-context.js";
import type { LocationSetting, LocationSettingInput, PriceInput, PriceRow, TaxRate } from "./pricing.types.js";
export async function hasPermission(c: DatabaseContext, permission: string): Promise<boolean> { const r = await sql<{ allowed: boolean }>`select app.has_business_permission(current_setting('app.business_id', true)::uuid, ${permission}) as allowed`.execute(c.transaction); return r.rows[0]?.allowed === true; }
export async function listPrices(c: DatabaseContext, businessId: string, filters: { productVariantId?: string; locationId?: string; assetCode?: string }): Promise<PriceRow[]> { const clauses: RawBuilder<unknown>[] = [sql`"businessId"=${businessId}::uuid`, sql`"status"='active'`]; if (filters.productVariantId) clauses.push(sql`"productVariantId"=${filters.productVariantId}::uuid`); if (filters.locationId) clauses.push(sql`"locationId"=${filters.locationId}::uuid`); if (filters.assetCode) clauses.push(sql`"assetCode"=${filters.assetCode}`); return (await sql<PriceRow>`select * from app.product_prices where ${sql.join(clauses, sql` and `)} order by "productVariantId","locationId" nulls first,"assetCode"`.execute(c.transaction)).rows; }
export async function createPrice(c: DatabaseContext, businessId: string, userId: string, input: PriceInput): Promise<PriceRow> { return (await sql<PriceRow>`insert into app.product_prices ("businessId","productVariantId","locationId","assetCode","amountMinor","compareAtMinor","effectiveFrom","effectiveTo","createdBy") values (${businessId}::uuid,${input.productVariantId}::uuid,${input.locationId ?? null}::uuid,${input.assetCode},${input.amountMinor},${input.compareAtMinor ?? null},coalesce(${input.effectiveFrom ?? null}::timestamptz, now()),${input.effectiveTo ?? null}::timestamptz,${userId}::uuid) returning *`.execute(c.transaction)).rows[0]!; }
export async function archivePrice(c: DatabaseContext, businessId: string, priceId: string): Promise<boolean> { return (await sql<{ id: string }>`update app.product_prices set "status"='archived',"archivedAt"=now() where "businessId"=${businessId}::uuid and "id"=${priceId}::uuid and "status"='active' returning "id"`.execute(c.transaction)).rows.length > 0; }
export async function resolvePrice(c: DatabaseContext, businessId: string, variantId: string, locationId: string | undefined, assetCode: string): Promise<PriceRow | undefined> { return (await sql<PriceRow>`select p.* from app.product_prices p where p."businessId"=${businessId}::uuid and p."productVariantId"=${variantId}::uuid and p."assetCode"=${assetCode} and p."status"='active' and p."effectiveFrom" <= now() and (p."effectiveTo" is null or p."effectiveTo" > now()) and (p."locationId" is null or p."locationId"=${locationId ?? null}::uuid) order by (p."locationId" is not null) desc, p."effectiveFrom" desc, p."id" limit 1`.execute(c.transaction)).rows[0]; }
export async function upsertLocationSetting(c: DatabaseContext, businessId: string, input: LocationSettingInput): Promise<LocationSetting> { return (await sql<LocationSetting>`insert into app.product_location_settings ("businessId","productId","locationId","isAvailable","leadTimeMinutes") values (${businessId}::uuid,${input.productId}::uuid,${input.locationId}::uuid,${input.isAvailable ?? true},${input.leadTimeMinutes ?? null}) on conflict ("businessId","productId","locationId") do update set "isAvailable"=excluded."isAvailable","leadTimeMinutes"=excluded."leadTimeMinutes" returning "id","businessId","productId","locationId","isAvailable","leadTimeMinutes",to_char("createdAt",'YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"') as "createdAt",to_char("updatedAt",'YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"') as "updatedAt"`.execute(c.transaction)).rows[0]!; }
export async function createTaxRate(c: DatabaseContext, businessId: string, input: { code: string; name: string; rateBps: number; isInclusive?: boolean; effectiveFrom?: string; effectiveTo?: string | null }): Promise<TaxRate> { return (await sql<TaxRate>`insert into app.tax_rates ("businessId","code","name","rateBps","isInclusive","effectiveFrom","effectiveTo") values (${businessId}::uuid,${input.code},${input.name},${input.rateBps},${input.isInclusive ?? false},coalesce(${input.effectiveFrom ?? null}::timestamptz,now()),${input.effectiveTo ?? null}::timestamptz) returning *`.execute(c.transaction)).rows[0]!; }
export async function listTaxRates(c: DatabaseContext, businessId: string): Promise<TaxRate[]> { return (await sql<TaxRate>`select * from app.tax_rates where "businessId"=${businessId}::uuid and "status"='active' order by "name"`.execute(c.transaction)).rows; }
