insert into app.permissions ("code", "description") values ('procurement.read','View procurement records'),('procurement.manage','Create purchase orders and receive goods') on conflict ("code") do nothing;
insert into app.role_permissions ("roleId","permissionId") select role."id", permission."id" from app.roles role cross join app.permissions permission where role."businessId" is null and role."code"='owner' and role."isSystem" on conflict do nothing;
create table app.supplier_products (
  "id" uuid primary key default gen_random_uuid(), "businessId" uuid not null, "supplierAccountId" uuid not null, "inventoryItemId" uuid not null,
  "supplierSku" text, "packSize" numeric(20,6) not null default 1 check ("packSize">0), "unitCostMinor" bigint not null check ("unitCostMinor">=0), "leadTimeDays" integer check ("leadTimeDays" is null or "leadTimeDays">=0), "minimumOrderQuantity" numeric(20,6) not null default 1 check ("minimumOrderQuantity">0), "isPreferred" boolean not null default false, "status" text not null default 'active' check ("status" in ('active','inactive','archived')), "createdAt" timestamptz not null default now(), "updatedAt" timestamptz not null default now(),
  unique ("businessId","supplierAccountId","inventoryItemId"), foreign key ("supplierAccountId","businessId") references app.supplier_accounts ("id","businessId") on delete restrict, foreign key ("inventoryItemId","businessId") references app.inventory_items ("id","businessId") on delete restrict
);
create table app.purchase_orders (
  "id" uuid primary key default gen_random_uuid(), "businessId" uuid not null, "supplierAccountId" uuid not null, "storeId" uuid not null, "status" text not null default 'draft' check ("status" in ('draft','approved','sent','partially_received','received','cancelled')), "orderNumber" text not null, "orderedAt" timestamptz, "expectedAt" timestamptz, "notes" text not null default '', "createdBy" uuid not null references auth.user("id") on delete restrict, "createdAt" timestamptz not null default now(), "updatedAt" timestamptz not null default now(), unique ("businessId","orderNumber"), unique ("id","businessId"), foreign key ("supplierAccountId","businessId") references app.supplier_accounts ("id","businessId") on delete restrict, foreign key ("storeId","businessId") references app.stores ("id","businessId") on delete restrict
);
create table app.purchase_order_lines (
  "id" uuid primary key default gen_random_uuid(), "businessId" uuid not null, "purchaseOrderId" uuid not null, "inventoryItemId" uuid not null, "quantityOrdered" numeric(20,6) not null check ("quantityOrdered">0), "quantityReceived" numeric(20,6) not null default 0 check ("quantityReceived">=0 and "quantityReceived" <= "quantityOrdered"), "unitCostMinor" bigint not null check ("unitCostMinor">=0), "createdAt" timestamptz not null default now(), unique ("id","businessId"), foreign key ("purchaseOrderId","businessId") references app.purchase_orders("id","businessId") on delete cascade, foreign key ("inventoryItemId","businessId") references app.inventory_items("id","businessId") on delete restrict
);
create table app.goods_receipts (
  "id" uuid primary key default gen_random_uuid(), "businessId" uuid not null, "purchaseOrderId" uuid not null, "inventoryLocationId" uuid not null, "status" text not null default 'posted' check ("status" in ('posted','voided')), "receivedAt" timestamptz not null default now(), "receivedBy" uuid not null references auth.user("id") on delete restrict, "idempotencyKey" text not null, "createdAt" timestamptz not null default now(), unique ("id","businessId"), unique ("businessId","idempotencyKey"), foreign key ("purchaseOrderId","businessId") references app.purchase_orders("id","businessId") on delete restrict, foreign key ("inventoryLocationId","businessId") references app.inventory_locations("id","businessId") on delete restrict
);
create table app.goods_receipt_lines (
  "id" uuid primary key default gen_random_uuid(), "businessId" uuid not null, "receiptId" uuid not null, "purchaseOrderLineId" uuid not null, "inventoryItemId" uuid not null, "quantityReceived" numeric(20,6) not null check ("quantityReceived">0), "quantityRejected" numeric(20,6) not null default 0 check ("quantityRejected">=0), "unitCostMinor" bigint not null check ("unitCostMinor">=0), "createdAt" timestamptz not null default now(), foreign key ("receiptId","businessId") references app.goods_receipts("id","businessId") on delete cascade, foreign key ("purchaseOrderLineId","businessId") references app.purchase_order_lines("id","businessId") on delete restrict, foreign key ("inventoryItemId","businessId") references app.inventory_items("id","businessId") on delete restrict
);
create trigger supplier_products_set_updated_at before update on app.supplier_products for each row execute function app.set_updated_at(); create trigger purchase_orders_set_updated_at before update on app.purchase_orders for each row execute function app.set_updated_at();
alter table app.supplier_products enable row level security; alter table app.purchase_orders enable row level security; alter table app.purchase_order_lines enable row level security; alter table app.goods_receipts enable row level security; alter table app.goods_receipt_lines enable row level security;
create policy supplier_products_read on app.supplier_products for select using (app.has_business_permission("businessId",'procurement.read')); create policy supplier_products_write on app.supplier_products for all using (app.has_business_permission("businessId",'procurement.manage')) with check (app.has_business_permission("businessId",'procurement.manage')); create policy purchase_orders_read on app.purchase_orders for select using (app.has_business_permission("businessId",'procurement.read')); create policy purchase_orders_write on app.purchase_orders for all using (app.has_business_permission("businessId",'procurement.manage')) with check (app.has_business_permission("businessId",'procurement.manage')); create policy purchase_order_lines_read on app.purchase_order_lines for select using (app.has_business_permission("businessId",'procurement.read')); create policy purchase_order_lines_write on app.purchase_order_lines for all using (app.has_business_permission("businessId",'procurement.manage')) with check (app.has_business_permission("businessId",'procurement.manage')); create policy goods_receipts_read on app.goods_receipts for select using (app.has_business_permission("businessId",'procurement.read')); create policy goods_receipts_write on app.goods_receipts for all using (app.has_business_permission("businessId",'procurement.manage')) with check (app.has_business_permission("businessId",'procurement.manage')); create policy goods_receipt_lines_read on app.goods_receipt_lines for select using (app.has_business_permission("businessId",'procurement.read')); create policy goods_receipt_lines_write on app.goods_receipt_lines for all using (app.has_business_permission("businessId",'procurement.manage')) with check (app.has_business_permission("businessId",'procurement.manage'));
grant select, insert, update on app.supplier_products, app.purchase_orders, app.purchase_order_lines, app.goods_receipts, app.goods_receipt_lines to scripe_app;
