alter table app.banking_profiles
  add column if not exists "businessType" text default 'limited_liability' check ("businessType" in ('sole_proprietorship', 'limited_liability', 'ngo_cooperative')),
  add column if not exists "registeredBusinessName" text,
  add column if not exists "registrationNumber" text,
  add column if not exists "taxIdentificationNumber" text,
  add column if not exists "website" text,
  add column if not exists "description" text,
  add column if not exists "businessCategory" text,
  add column if not exists "annualRevenue" text,
  add column if not exists "businessAddress" jsonb,
  add column if not exists "directorNin" text,
  add column if not exists "directorDob" text,
  add column if not exists "directorIdType" text,
  add column if not exists "directorIdDocumentUrl" text,
  add column if not exists "certificateOfIncorporationUrl" text,
  add column if not exists "statusReportUrl" text,
  add column if not exists "proofOfAddressUrl" text,
  add column if not exists "settlementBankCode" text,
  add column if not exists "settlementAccountNumber" text,
  add column if not exists "settlementAccountName" text;
