/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface UserProfiles {
  createdAt: Generated<Timestamp>;
  email: string;
  image: string | null;
  name: Generated<string>;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface DB {
  user_profiles: UserProfiles;
}
