import type { Database } from "../../db/database.types.js";
import { sql } from "kysely";
import { withDatabaseContext } from "../../db/database-context.js";
import { DatabaseError, normalizeDatabaseError } from "../../db/errors.js";
import { withIdentity } from "../../db/principal.js";
import { AppError, conflictError, forbiddenError, notFoundError } from "../../shared/errors.js";
import * as repo from "./carts.repository.js";
import * as orderRepo from "../orders/orders.repository.js";
import type { AddCartLineInput, Cart, CartLine, CartOperation, CheckoutInput, CreateCartInput, UpdateCartLineInput } from "./carts.types.js";
export class CartsService {
  constructor(private readonly database: Database) {}
  async create(op: CartOperation, input: CreateCartInput): Promise<Cart> { return this.run(op, async (c) => { await this.require(c, "cart.manage"); return this.hydrate(await repo.createCart(c, op.businessId, op.userId, input), c); }); }
  async get(op: CartOperation, cartId: string): Promise<Cart> { return this.run(op, async (c) => { await this.require(c, "cart.read"); const row = await repo.findCart(c, op.businessId, cartId); if (!row) throw notFoundError("Cart not found"); return this.hydrate(row, c); }); }
  async addLine(op: CartOperation, cartId: string, input: AddCartLineInput): Promise<Cart> { return this.run(op, async (c) => { await this.require(c, "cart.manage"); const cart = await repo.findCart(c, op.businessId, cartId, true); if (!cart || cart.status !== "active") throw notFoundError("Active cart not found"); await repo.addLine(c, op.businessId, cartId, input); return this.hydrate(cart, c); }); }
  async updateLine(op: CartOperation, cartId: string, lineId: string, input: UpdateCartLineInput): Promise<Cart> { return this.run(op, async (c) => { await this.require(c, "cart.manage"); const cart = await repo.findCart(c, op.businessId, cartId); if (!cart || cart.status !== "active") throw notFoundError("Active cart not found"); if (!(await repo.updateLine(c, op.businessId, cartId, lineId, input))) throw notFoundError("Cart line not found"); return this.hydrate(cart, c); }); }
  async deleteLine(op: CartOperation, cartId: string, lineId: string): Promise<Cart> { return this.run(op, async (c) => { await this.require(c, "cart.manage"); const cart = await repo.findCart(c, op.businessId, cartId); if (!cart || cart.status !== "active") throw notFoundError("Active cart not found"); if (!(await repo.deleteLine(c, op.businessId, cartId, lineId))) throw notFoundError("Cart line not found"); return this.hydrate(cart, c); }); }
  async checkout(op: CartOperation, cartId: string, input: CheckoutInput): Promise<{ orderId: string }> { return this.run(op, async (c) => { await this.require(c, "cart.manage"); await this.require(c, "order.create"); const previous = await repo.findCheckout(c, op.businessId, input.idempotencyKey); if (previous?.orderId) return { orderId: previous.orderId }; if (previous) throw conflictError("Checkout idempotency key is already in progress"); const cart = await repo.findCart(c, op.businessId, cartId, true); if (!cart || cart.status !== "active") throw notFoundError("Active cart not found"); const lines = await repo.listLines(c, op.businessId, cartId); if (!lines.length) throw conflictError("Cannot checkout an empty cart"); await repo.createCheckout(c, op.businessId, cartId, input.idempotencyKey); const order = await orderRepo.createFromCart(c, op.businessId, op.userId, cart, lines, input.locationId ?? null); await repo.markConverted(c, op.businessId, cartId); await repo.linkCheckout(c, op.businessId, input.idempotencyKey, order.id); return { orderId: order.id }; }); }
  private async hydrate(row: Awaited<ReturnType<typeof repo.findCart>> extends infer R ? Exclude<R, undefined> : never, c: Parameters<typeof repo.findCart>[0]): Promise<Cart> { const lines = await repo.listLines(c, row.businessId, row.id); return { ...row, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString(), convertedAt: row.convertedAt?.toISOString() ?? null, lines: lines.map(toLine) }; }
  private async require(c: Parameters<typeof repo.findCart>[0], permission: string): Promise<void> { const result = await sql<{ allowed: boolean }>`select app.has_business_permission(current_setting('app.business_id', true)::uuid, ${permission}) as allowed`.execute(c.transaction); if (result.rows[0]?.allowed !== true) throw forbiddenError(`Missing permission: ${permission}`); }
  private async run<T>(op: CartOperation, work: Parameters<typeof withDatabaseContext<T>>[2]): Promise<T> { try { return await withDatabaseContext(this.database, withIdentity(op.requestId, op.userId, op.businessId), work); } catch (error) { if (error instanceof AppError || error instanceof DatabaseError) throw error; throw normalizeDatabaseError(error); } }
}
function toLine(row: Awaited<ReturnType<typeof repo.listLines>>[number]): CartLine { return { ...row, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() }; }
