/**
 * Database access for the bill, bill line, and bill payment allocation domain belongs
 * here. Repository functions must accept DatabaseContext and must not import the global
 * database.
 */
import { sql } from "kysely";
import type { DatabaseContext } from "../../db/database-context.js";
import type { AllocatePaymentInput, CreateBillInput } from "./payables.types.js";
export async function hasPermission(c: DatabaseContext, permission: string): Promise<boolean> { const r = await sql<{ allowed: boolean }>`select app.has_business_permission(current_setting('app.business_id',true)::uuid,${permission}) as allowed`.execute(c.transaction); return r.rows[0]?.allowed === true; }
export async function createBill(c: DatabaseContext, businessId: string, userId: string, input: CreateBillInput): Promise<{ id: string }> { const bill = (await sql<{ id: string }>`insert into app.bills ("businessId","supplierAccountId","billNumber","billType","assetCode","issuedAt","dueAt","subtotalMinor","taxMinor","totalMinor","notes","createdBy") values (${businessId}::uuid,${input.supplierAccountId ?? null}::uuid,${input.billNumber},${input.billType ?? 'supplier'},${input.assetCode ?? 'NGN'},${input.issuedAt ?? null}::date,${input.dueAt ?? null}::date,${input.subtotalMinor},${input.taxMinor ?? 0},${input.totalMinor},${input.notes ?? ''},${userId}::uuid) returning "id"`.execute(c.transaction)).rows[0]!; for (const line of input.lines) await sql`insert into app.bill_lines ("businessId","billId","description","quantity","unitAmountMinor","taxMinor","lineTotalMinor","accountCategory","purchaseOrderId","purchaseOrderLineId","goodsReceiptId") values (${businessId}::uuid,${bill.id}::uuid,${line.description},${line.quantity},${line.unitAmountMinor},${line.taxMinor ?? 0},${line.lineTotalMinor},${line.accountCategory},${line.purchaseOrderId ?? null}::uuid,${line.purchaseOrderLineId ?? null}::uuid,${line.goodsReceiptId ?? null}::uuid)`.execute(c.transaction); return bill; }
export async function allocatePayment(c: DatabaseContext, businessId: string, userId: string, billId: string, input: AllocatePaymentInput): Promise<{ id: string } | null> { const result = await sql<{ id: string }>`insert into app.bill_payment_allocations ("businessId","billId","paymentReference","amountMinor","assetCode","paidAt","createdBy") select ${businessId}::uuid, b."id", ${input.paymentReference}, ${input.amountMinor}, ${input.assetCode}, ${input.paidAt ?? null}::timestamptz, ${userId}::uuid from app.bills b where b."id"=${billId}::uuid and b."businessId"=${businessId}::uuid and b."status" <> 'voided' and b."assetCode"=${input.assetCode} and b."amountPaidMinor" + ${input.amountMinor} <= b."totalMinor" returning "id"`.execute(c.transaction); const allocation = result.rows[0]; if (!allocation) return null; await sql`update app.bills set "amountPaidMinor"="amountPaidMinor"+${input.amountMinor}, "status"=case when "amountPaidMinor"+${input.amountMinor} = "totalMinor" then 'paid' else 'partially_paid' end where "id"=${billId}::uuid and "businessId"=${businessId}::uuid`.execute(c.transaction); return allocation; }
