import { sql } from "kysely";
import type { DatabaseContext } from "../../db/database-context.js";
import type { AddCartLineInput, CartLineRow, CartRow, CreateCartInput, UpdateCartLineInput } from "./carts.types.js";
export async function findCart(c: DatabaseContext, businessId: string, cartId: string, lock = false): Promise<CartRow | undefined> { return (await sql<CartRow>`select * from app.carts where "businessId"=${businessId}::uuid and "id"=${cartId}::uuid ${lock ? sql`for update` : sql``}`.execute(c.transaction)).rows[0]; }
export async function listLines(c: DatabaseContext, businessId: string, cartId: string): Promise<CartLineRow[]> { return (await sql<CartLineRow>`select * from app.cart_lines where "businessId"=${businessId}::uuid and "cartId"=${cartId}::uuid order by "createdAt","id"`.execute(c.transaction)).rows; }
export async function createCart(c: DatabaseContext, businessId: string, userId: string, input: CreateCartInput): Promise<CartRow> { return (await sql<CartRow>`insert into app.carts ("businessId","storeId","channelId","customerPartyId","currency","createdBy") values (${businessId}::uuid,${input.storeId}::uuid,${input.channelId}::uuid,${input.customerPartyId ?? null}::uuid,${input.currency ?? "NGN"},${userId}::uuid) returning *`.execute(c.transaction)).rows[0]!; }
export async function addLine(c: DatabaseContext, businessId: string, cartId: string, input: AddCartLineInput): Promise<CartLineRow> { return (await sql<CartLineRow>`insert into app.cart_lines ("businessId","cartId","productVariantId","quantity","selectedModifiers","assetCode") values (${businessId}::uuid,${cartId}::uuid,${input.productVariantId}::uuid,${input.quantity},${JSON.stringify(input.selectedModifiers ?? {})}::jsonb,${input.assetCode ?? "NGN"}) on conflict ("cartId","productVariantId","businessId") do update set "quantity"=app.cart_lines."quantity"+excluded."quantity","selectedModifiers"=excluded."selectedModifiers","assetCode"=excluded."assetCode" returning *`.execute(c.transaction)).rows[0]!; }
export async function updateLine(c: DatabaseContext, businessId: string, cartId: string, lineId: string, input: UpdateCartLineInput): Promise<CartLineRow | undefined> { return (await sql<CartLineRow>`update app.cart_lines set "quantity"=${input.quantity},"selectedModifiers"=coalesce(${input.selectedModifiers ? JSON.stringify(input.selectedModifiers) : null}::jsonb,"selectedModifiers") where "businessId"=${businessId}::uuid and "cartId"=${cartId}::uuid and "id"=${lineId}::uuid returning *`.execute(c.transaction)).rows[0]; }
export async function deleteLine(c: DatabaseContext, businessId: string, cartId: string, lineId: string): Promise<boolean> { const result = await sql`delete from app.cart_lines where "businessId"=${businessId}::uuid and "cartId"=${cartId}::uuid and "id"=${lineId}::uuid`.execute(c.transaction); return (result.numAffectedRows ?? 0n) > 0n; }
export async function markConverted(c: DatabaseContext, businessId: string, cartId: string): Promise<void> { await sql`update app.carts set "status"='converted',"convertedAt"=now() where "businessId"=${businessId}::uuid and "id"=${cartId}::uuid`.execute(c.transaction); }
export async function findCheckout(c: DatabaseContext, businessId: string, key: string): Promise<{ orderId: string | null; status: string } | undefined> { return (await sql<{ orderId: string | null; status: string }>`select "orderId", "status" from app.checkout_sessions where "businessId"=${businessId}::uuid and "idempotencyKey"=${key} limit 1`.execute(c.transaction)).rows[0]; }
export async function createCheckout(c: DatabaseContext, businessId: string, cartId: string, key: string): Promise<void> { await sql`insert into app.checkout_sessions ("businessId","cartId","expiresAt","idempotencyKey") values (${businessId}::uuid,${cartId}::uuid,now()+interval '20 minutes',${key})`.execute(c.transaction); }
export async function linkCheckout(c: DatabaseContext, businessId: string, key: string, orderId: string): Promise<void> { await sql`update app.checkout_sessions set "status"='converted',"orderId"=${orderId}::uuid,"convertedAt"=now() where "businessId"=${businessId}::uuid and "idempotencyKey"=${key}`.execute(c.transaction); }
